# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 68b759b06fcbdab0f5ec7bf84dc804c40f3a01c218b1f615b8407db7940ef4e742c711628dfd4677e8bf0aff3c3b40a13d65cdaf6a684d692f9d17b6848d8be3

test:
  secret_key_base: 9bdefce65e9c61ef1f43d0251f75964ee1817c1e10718d4bd6f6a10f0dc9ec5023eef037c6054c2057f753f3530bfa18cfabe403c2f831b81b25d317e9576188

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
